# For instructions on how to enable this hook run see `./README.md`
# This script will run the Ruff linter and formatter on all files in the repository.
# More information: https://github.com/astral-sh/ruff-pre-commit
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.7
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
